[window]
padding = { x = 15, y = 15 }
opacity = 0.50

[scrolling]
history = 1000
multiplier = 6

[font]
normal = { family = "JetBrains Mono Nerd Font", style = "Regular" }
bold = { family = "JetBrains Mono Nerd Font", style = "Bold" }
bold_italic = { family = "JetBrains Mono Nerd Font", style = "Bold Italic" }
size = 11

[keyboard]
bindings = [
{ key = "+", mods = "Control|Shift", action = "IncreaseFontSize" },
{ key = "_", mods = "Control|Shift", action = "DecreaseFontSize" },
{ key = "Backspace", mods = "Control|Shift", action = "ResetFontSize" },
]
